#!/bin/sh
export TERM=xterm-256color

# This should contain:
# - sniper-runtime/ - extracted sniper runtime images
# - proton/ - proton to be mounted in container
# - home/ - persistent home
DATA=$HOME/.local/share/minipv

# Overrides
OVERRIDES="$(dirname $(readlink -f "$0"))/overrides"

# Compat data folder must exist or proton exits
mkdir -p $DATA/home/steamcompat

args=(
  --clearenv
  --unshare-all

  --size 90000000000 --tmpfs /

  --ro-bind "$DATA/sniper-runtime/files" /usr

  --dev-bind /dev /dev
  --bind /opt /opt
  --proc /proc
  --bind /run/user /run/user
  --bind /srv /srv
  --bind /sys /sys
  --bind /tmp /tmp
  --bind /var /var

  --symlink usr/bin /bin
  --symlink usr/sbin /sbin
  --symlink usr/lib /lib
  --symlink usr/lib32 /lib32
  --symlink usr/lib64 /lib64

  # host
  --ro-bind /usr /run/host/usr

  # /etc
  --ro-bind /etc/fonts /etc/fonts
  --symlink /usr/lib/os-release /etc/os-release

  # fake configs
  --file 11 /etc/passwd
  --file 12 /etc/group
  --file 13 /etc/machine-id

  # env
  --setenv DISPLAY $DISPLAY
  --setenv WAYLAND_DISPLAY $WAYLAND_DISPLAY
  --setenv XDG_RUNTIME_DIR $XDG_RUNTIME_DIR
  --setenv XDG_DATA_DIRS /overrides/share:/usr/local/share:/usr/share
  --setenv PATH /usr/bin:/bin:/proton

  # user
  --setenv USER ${USER}
  --setenv HOME /home/${USER}
  --bind $DATA/home /home/${USER}
  --bind-try cache /home/${USER}/.cache
  --bind-try config /home/${USER}/.config
  --bind-try local /home/${USER}/.local
  --bind-try users /home/${USER}/steamcompat/pfx/drive_c/users

  # library overrides
  --ro-bind "${OVERRIDES}/etc/ld.so.conf" /etc/ld.so.conf
  --ro-bind "${DATA}/sniper-runtime/files/etc/ld.so.conf.d" /etc/ld.so.conf.d
  --ro-bind /usr/lib/ld-linux-x86-64.so.2 /usr/lib/x86_64-linux-gnu/ld-2.31.so
  --ro-bind /usr/lib32/ld-linux.so.2 /usr/lib/i386-linux-gnu/ld-2.31.so
  --ro-bind /usr/bin/ldd /usr/bin/ldd
  --setenv LD_LIBRARY_PATH /overrides/lib/x86_64-linux-gnu:/overrides/lib/i386-linux-gnu

  # Vulkan
  --ro-bind "${OVERRIDES}/share/vulkan/icd.d/radeon_icd.x86_64.json" /overrides/share/vulkan/icd.d/radeon_icd.x86_64.json
  --ro-bind "${OVERRIDES}/share/vulkan/icd.d/radeon_icd.i686.json" /overrides/share/vulkan/icd.d/radeon_icd.i686.json
  --ro-bind "${OVERRIDES}/share/vulkan/icd.d/intel_icd.x86_64.json" /overrides/share/vulkan/icd.d/intel_icd.x86_64.json
  --ro-bind "${OVERRIDES}/share/vulkan/icd.d/intel_icd.i686.json" /overrides/share/vulkan/icd.d/intel_icd.i686.json

  # Mangohud
  --ro-bind "${OVERRIDES}/share/vulkan/implicit_layer.d/MangoHud.x86_64.json" /overrides/share/vulkan/implicit_layer.d/MangoHud.x86_64.json
  --ro-bind "${OVERRIDES}/share/vulkan/implicit_layer.d/MangoHud.x86.json" /overrides/share/vulkan/implicit_layer.d/MangoHud.x86.json
  --setenv MANGOHUD 1
  # --setenv MANGOHUD_CONFIG full
  --setenv LD_PRELOAD "/run/host/usr/\$LIB/mangohud/libMangoHud_shim.so:libgamemodeauto.so.0"

  # Proton
  --ro-bind "${DATA}/proton" /proton
  --setenv STEAM_COMPAT_CLIENT_INSTALL_PATH ""
  --setenv STEAM_COMPAT_DATA_PATH /home/${USER}/steamcompat
  --setenv SteamGameId 0
  --setenv UMU_ID 0

  # Fix for hotplug controllers inside bubblewrap
  # (udev detection doesn't seem to work with --unshare-net)
  --setenv SDL_JOYSTICK_DISABLE_UDEV 1

  # app
  --bind-try app /home/${USER}/app
)

add_symlink() {
  arch="$1"
  src="$2"
  dst="$3"
  if [ -e "$src" ]; then
    args+=(--symlink "/run/host/$src" "/overrides/lib/$arch/$dst")
  else
    echo "Warning: source file $src does not exist, skipping symlink to $dst" >&2
  fi
}

# 64 bit
add_symlink x86_64-linux-gnu /usr/lib/libanl.so.1 libanl.so.1
add_symlink x86_64-linux-gnu /usr/lib/libBrokenLocale.so.1 libBrokenLocale.so.1
add_symlink x86_64-linux-gnu /usr/lib/libcap.so.2.76 libcap.so.2
add_symlink x86_64-linux-gnu /usr/lib/libc.so.6 libc.so.6
add_symlink x86_64-linux-gnu /usr/lib/libdbus-1.so.3 libdbus-1.so.3
add_symlink x86_64-linux-gnu /usr/lib/libdl.so.2 libdl.so.2
add_symlink x86_64-linux-gnu /usr/lib/libdrm_amdgpu.so.1.125.0 libdrm_amdgpu.so.1
add_symlink x86_64-linux-gnu /usr/lib/libdrm_intel.so.1.125.0 libdrm_intel.so.1
add_symlink x86_64-linux-gnu /usr/lib/libdrm_nouveau.so.2.125.0 libdrm_nouveau.so.2
add_symlink x86_64-linux-gnu /usr/lib/libdrm_radeon.so.1.125.0 libdrm_radeon.so.1
add_symlink x86_64-linux-gnu /usr/lib/libdrm.so.2.125.0 libdrm.so.2
add_symlink x86_64-linux-gnu /usr/lib/libedit.so.0.0.75 libedit.so.0
add_symlink x86_64-linux-gnu /usr/lib/libEGL_mesa.so.0.0.0 libEGL_mesa.so.0
add_symlink x86_64-linux-gnu /usr/lib/libEGL.so.1.1.0 libEGL.so.1
add_symlink x86_64-linux-gnu /usr/lib/libelf-0.193.so libelf.so.1
add_symlink x86_64-linux-gnu /usr/lib/libexpat.so.1.10.2 libexpat.so.1
add_symlink x86_64-linux-gnu /usr/lib/libffi.so.8 libffi.so.8
add_symlink x86_64-linux-gnu /usr/lib/libgallium-25.1.7-arch1.1.so libgallium-25.1.7-arch1.1.so
add_symlink x86_64-linux-gnu /usr/lib/libgamemode.so.0 libgamemode.so.0
add_symlink x86_64-linux-gnu /usr/lib/libgamemodeauto.so.0 libgamemodeauto.so.0
add_symlink x86_64-linux-gnu /usr/lib/libgbm.so.1.0.0 libgbm.so.1
add_symlink x86_64-linux-gnu /usr/lib/libgcc_s.so.1 libgcc_s.so.1
add_symlink x86_64-linux-gnu /usr/lib/libGLdispatch.so.0.0.0 libGLdispatch.so.0
add_symlink x86_64-linux-gnu /usr/lib/libGLESv2.so.2.1.0 libGLESv2.so.2
add_symlink x86_64-linux-gnu /usr/lib/libGL.so.1.7.0 libGL.so.1
add_symlink x86_64-linux-gnu /usr/lib/libGLX_mesa.so.0.0.0 libGLX_indirect.so.0
add_symlink x86_64-linux-gnu /usr/lib/libGLX_mesa.so.0.0.0 libGLX_mesa.so.0
add_symlink x86_64-linux-gnu /usr/lib/libGLX.so.0.0.0 libGLX.so.0
add_symlink x86_64-linux-gnu /usr/lib/libicudata.so.76.1 libicudata.so.76
add_symlink x86_64-linux-gnu /usr/lib/libicuuc.so.76.1 libicuuc.so.76
add_symlink x86_64-linux-gnu /usr/lib/libidn2.so.0.4.0 libidn2.so.0
add_symlink x86_64-linux-gnu /usr/lib/libLLVM.so.20.1 libLLVM.so.20.1
add_symlink x86_64-linux-gnu /usr/lib/liblzma.so.5.8.1 liblzma.so.5
add_symlink x86_64-linux-gnu /usr/lib/libmemusage.so libmemusage.so
add_symlink x86_64-linux-gnu /usr/lib/libm.so.6 libm.so.6
add_symlink x86_64-linux-gnu /usr/lib/libmvec.so.1 libmvec.so.1
add_symlink x86_64-linux-gnu /usr/lib/libncursesw.so.6.5 libncursesw.so.6
add_symlink x86_64-linux-gnu /usr/lib/libnsl.so.1 libnsl.so.1
add_symlink x86_64-linux-gnu /usr/lib/libnss_compat.so.2 libnss_compat.so.2
add_symlink x86_64-linux-gnu /usr/lib/libnss_db.so.2 libnss_db.so.2
add_symlink x86_64-linux-gnu /usr/lib/libnss_dns.so.2 libnss_dns.so.2
add_symlink x86_64-linux-gnu /usr/lib/libnss_files.so.2 libnss_files.so.2
add_symlink x86_64-linux-gnu /usr/lib/libOpenCL.so.1.0.0 libOpenCL.so.1
add_symlink x86_64-linux-gnu /usr/lib/libOpenGL.so.0.0.0 libOpenGL.so.0
add_symlink x86_64-linux-gnu /usr/lib/libpciaccess.so.0.11.1 libpciaccess.so.0
add_symlink x86_64-linux-gnu /usr/lib/libpcprofile.so libpcprofile.so
add_symlink x86_64-linux-gnu /usr/lib/libpthread.so.0 libpthread.so.0
add_symlink x86_64-linux-gnu /usr/lib/libresolv.so.2 libresolv.so.2
add_symlink x86_64-linux-gnu /usr/lib/librt.so.1 librt.so.1
add_symlink x86_64-linux-gnu /usr/lib/libsensors.so.5.0.0 libsensors.so.5
add_symlink x86_64-linux-gnu /usr/lib/libSPIRV-Tools.so libSPIRV-Tools.so
add_symlink x86_64-linux-gnu /usr/lib/libstdc++.so.6.0.34 libstdc++.so.6
add_symlink x86_64-linux-gnu /usr/lib/libsystemd.so.0.40.0 libsystemd.so.0
add_symlink x86_64-linux-gnu /usr/lib/libthread_db.so.1 libthread_db.so.1
add_symlink x86_64-linux-gnu /usr/lib/libudev.so.1.7.10 libudev.so.1
add_symlink x86_64-linux-gnu /usr/lib/libunistring.so.5.2.0 libunistring.so.5
add_symlink x86_64-linux-gnu /usr/lib/libutil.so.1 libutil.so.1
add_symlink x86_64-linux-gnu /usr/lib/libva-drm.so.2.2200.0 libva-drm.so.2
add_symlink x86_64-linux-gnu /usr/lib/libva-glx.so.2.2200.0 libva-glx.so.2
add_symlink x86_64-linux-gnu /usr/lib/libva.so.2.2200.0 libva.so.2
add_symlink x86_64-linux-gnu /usr/lib/libva-x11.so.2.2200.0 libva-x11.so.2
add_symlink x86_64-linux-gnu /usr/lib/libvdpau.so.1.0.0 libvdpau.so.1
add_symlink x86_64-linux-gnu /usr/lib/libvulkan.so.1.4.321 libvulkan.so.1
add_symlink x86_64-linux-gnu /usr/lib/libwayland-client.so.0.24.0 libwayland-client.so.0
add_symlink x86_64-linux-gnu /usr/lib/libwayland-server.so.0.24.0 libwayland-server.so.0
add_symlink x86_64-linux-gnu /usr/lib/libX11.so.6.4.0 libX11.so.6
add_symlink x86_64-linux-gnu /usr/lib/libX11-xcb.so.1.0.0 libX11-xcb.so.1
add_symlink x86_64-linux-gnu /usr/lib/libXau.so.6.0.0 libXau.so.6
add_symlink x86_64-linux-gnu /usr/lib/libxcb-dri3.so.0.1.0 libxcb-dri3.so.0
add_symlink x86_64-linux-gnu /usr/lib/libxcb-glx.so.0.0.0 libxcb-glx.so.0
add_symlink x86_64-linux-gnu /usr/lib/libxcb-keysyms.so.1.0.0 libxcb-keysyms.so.1
add_symlink x86_64-linux-gnu /usr/lib/libxcb-present.so.0.0.0 libxcb-present.so.0
add_symlink x86_64-linux-gnu /usr/lib/libxcb-randr.so.0.1.0 libxcb-randr.so.0
add_symlink x86_64-linux-gnu /usr/lib/libxcb-shm.so.0.0.0 libxcb-shm.so.0
add_symlink x86_64-linux-gnu /usr/lib/libxcb.so.1.1.0 libxcb.so.1
add_symlink x86_64-linux-gnu /usr/lib/libxcb-sync.so.1.0.0 libxcb-sync.so.1
add_symlink x86_64-linux-gnu /usr/lib/libxcb-xfixes.so.0.0.0 libxcb-xfixes.so.0
add_symlink x86_64-linux-gnu /usr/lib/libxcb-xkb.so.1.0.0 libxcb-xkb.so.1
add_symlink x86_64-linux-gnu /usr/lib/libXdmcp.so.6.0.0 libXdmcp.so.6
add_symlink x86_64-linux-gnu /usr/lib/libXext.so.6.4.0 libXext.so.6
add_symlink x86_64-linux-gnu /usr/lib/libXfixes.so.3.1.0 libXfixes.so.3
add_symlink x86_64-linux-gnu /usr/lib/libxkbcommon.so.0.10.0 libxkbcommon.so.0
add_symlink x86_64-linux-gnu /usr/lib/libxkbcommon-x11.so.0.10.0 libxkbcommon-x11.so.0
add_symlink x86_64-linux-gnu /usr/lib/libxml2.so.16.0.5 libxml2.so.16
# add_symlink x86_64-linux-gnu /usr/lib/libXNVCtrl.so.0.0.0 libXNVCtrl.so.0
add_symlink x86_64-linux-gnu /usr/lib/libxshmfence.so.1.0.0 libxshmfence.so.1
add_symlink x86_64-linux-gnu /usr/lib/libXxf86vm.so.1.0.0 libXxf86vm.so.1
add_symlink x86_64-linux-gnu /usr/lib/libz.so.1.3.1 libz.so.1
add_symlink x86_64-linux-gnu /usr/lib/libzstd.so.1.5.7 libzstd.so.1

# 32 bit
add_symlink i386-linux-gnu /usr/lib32/libanl.so.1 libanl.so.1
add_symlink i386-linux-gnu /usr/lib32/libBrokenLocale.so.1 libBrokenLocale.so.1
add_symlink i386-linux-gnu /usr/lib32/libcap.so.2.76 libcap.so.2
add_symlink i386-linux-gnu /usr/lib32/libc.so.6 libc.so.6
add_symlink i386-linux-gnu /usr/lib32/libdbus-1.so.3 libdbus-1.so.3
add_symlink i386-linux-gnu /usr/lib32/libdl.so.2 libdl.so.2
add_symlink i386-linux-gnu /usr/lib32/libdrm_amdgpu.so.1.125.0 libdrm_amdgpu.so.1
add_symlink i386-linux-gnu /usr/lib32/libdrm_intel.so.1.125.0 libdrm_intel.so.1
add_symlink i386-linux-gnu /usr/lib32/libdrm_nouveau.so.2.125.0 libdrm_nouveau.so.2
add_symlink i386-linux-gnu /usr/lib32/libdrm_radeon.so.1.125.0 libdrm_radeon.so.1
add_symlink i386-linux-gnu /usr/lib32/libdrm.so.2.125.0 libdrm.so.2
add_symlink i386-linux-gnu /usr/lib32/libEGL_mesa.so.0.0.0 libEGL_mesa.so.0
add_symlink i386-linux-gnu /usr/lib32/libEGL.so.1.1.0 libEGL.so.1
add_symlink i386-linux-gnu /usr/lib32/libelf-0.193.so libelf.so.1
add_symlink i386-linux-gnu /usr/lib32/libexpat.so.1.10.2 libexpat.so.1
add_symlink i386-linux-gnu /usr/lib32/libffi.so.8 libffi.so.8
add_symlink i386-linux-gnu /usr/lib32/libgallium-25.1.7-arch1.1.so libgallium-25.1.7-arch1.1.so
add_symlink i386-linux-gnu /usr/lib32/libgamemode.so.0 libgamemode.so.0
add_symlink i386-linux-gnu /usr/lib32/libgamemodeauto.so.0 libgamemodeauto.so.0
add_symlink i386-linux-gnu /usr/lib32/libgbm.so.1.0.0 libgbm.so.1
add_symlink i386-linux-gnu /usr/lib32/libgcc_s.so.1 libgcc_s.so.1
add_symlink i386-linux-gnu /usr/lib32/libGLdispatch.so.0.0.0 libGLdispatch.so.0
add_symlink i386-linux-gnu /usr/lib32/libGLESv2.so.2.1.0 libGLESv2.so.2
add_symlink i386-linux-gnu /usr/lib32/libGL.so.1.7.0 libGL.so.1
add_symlink i386-linux-gnu /usr/lib32/libGLX_mesa.so.0.0.0 libGLX_mesa.so.0
add_symlink i386-linux-gnu /usr/lib32/libGLX.so.0.0.0 libGLX.so.0
add_symlink i386-linux-gnu /usr/lib32/libicudata.so.76.1 libicudata.so.76
add_symlink i386-linux-gnu /usr/lib32/libicuuc.so.76.1 libicuuc.so.76
add_symlink i386-linux-gnu /usr/lib32/libidn2.so.0.4.0 libidn2.so.0
add_symlink i386-linux-gnu /usr/lib32/libLLVM.so.20.1 libLLVM.so.20.1
add_symlink i386-linux-gnu /usr/lib32/liblzma.so.5.8.1 liblzma.so.5
add_symlink i386-linux-gnu /usr/lib32/libmemusage.so libmemusage.so
add_symlink i386-linux-gnu /usr/lib32/libm.so.6 libm.so.6
add_symlink i386-linux-gnu /usr/lib32/libnsl.so.1 libnsl.so.1
add_symlink i386-linux-gnu /usr/lib32/libnss_compat.so.2 libnss_compat.so.2
add_symlink i386-linux-gnu /usr/lib32/libnss_db.so.2 libnss_db.so.2
add_symlink i386-linux-gnu /usr/lib32/libnss_dns.so.2 libnss_dns.so.2
add_symlink i386-linux-gnu /usr/lib32/libnss_files.so.2 libnss_files.so.2
add_symlink i386-linux-gnu /usr/lib32/libOpenGL.so.0.0.0 libOpenGL.so.0
add_symlink i386-linux-gnu /usr/lib32/libpciaccess.so.0.11.1 libpciaccess.so.0
add_symlink i386-linux-gnu /usr/lib32/libpcprofile.so libpcprofile.so
add_symlink i386-linux-gnu /usr/lib32/libpthread.so.0 libpthread.so.0
add_symlink i386-linux-gnu /usr/lib32/libresolv.so.2 libresolv.so.2
add_symlink i386-linux-gnu /usr/lib32/librt.so.1 librt.so.1
add_symlink i386-linux-gnu /usr/lib32/libsensors.so.5.0.0 libsensors.so.5
add_symlink i386-linux-gnu /usr/lib32/libSPIRV-Tools.so libSPIRV-Tools.so
add_symlink i386-linux-gnu /usr/lib32/libstdc++.so.6.0.34 libstdc++.so.6
add_symlink i386-linux-gnu /usr/lib32/libsystemd.so.0.40.0 libsystemd.so.0
add_symlink i386-linux-gnu /usr/lib32/libthread_db.so.1 libthread_db.so.1
add_symlink i386-linux-gnu /usr/lib32/libudev.so.1.7.10 libudev.so.1
add_symlink i386-linux-gnu /usr/lib32/libunistring.so.5.2.0 libunistring.so.5
add_symlink i386-linux-gnu /usr/lib32/libutil.so.1 libutil.so.1
add_symlink i386-linux-gnu /usr/lib32/libva-drm.so.2.2200.0 libva-drm.so.2
add_symlink i386-linux-gnu /usr/lib32/libva-glx.so.2.2200.0 libva-glx.so.2
add_symlink i386-linux-gnu /usr/lib32/libva.so.2.2200.0 libva.so.2
add_symlink i386-linux-gnu /usr/lib32/libva-x11.so.2.2200.0 libva-x11.so.2
add_symlink i386-linux-gnu /usr/lib32/libvulkan.so.1.4.321 libvulkan.so.1
add_symlink i386-linux-gnu /usr/lib32/libwayland-client.so.0.23.1 libwayland-client.so.0
add_symlink i386-linux-gnu /usr/lib32/libwayland-server.so.0.23.1 libwayland-server.so.0
add_symlink i386-linux-gnu /usr/lib32/libX11.so.6.4.0 libX11.so.6
add_symlink i386-linux-gnu /usr/lib32/libX11-xcb.so.1.0.0 libX11-xcb.so.1
add_symlink i386-linux-gnu /usr/lib32/libXau.so.6.0.0 libXau.so.6
add_symlink i386-linux-gnu /usr/lib32/libxcb-dri3.so.0.1.0 libxcb-dri3.so.0
add_symlink i386-linux-gnu /usr/lib32/libxcb-glx.so.0.0.0 libxcb-glx.so.0
add_symlink i386-linux-gnu /usr/lib32/libxcb-keysyms.so.1.0.0 libxcb-keysyms.so.1
add_symlink i386-linux-gnu /usr/lib32/libxcb-present.so.0.0.0 libxcb-present.so.0
add_symlink i386-linux-gnu /usr/lib32/libxcb-randr.so.0.1.0 libxcb-randr.so.0
add_symlink i386-linux-gnu /usr/lib32/libxcb-shm.so.0.0.0 libxcb-shm.so.0
add_symlink i386-linux-gnu /usr/lib32/libxcb.so.1.1.0 libxcb.so.1
add_symlink i386-linux-gnu /usr/lib32/libxcb-sync.so.1.0.0 libxcb-sync.so.1
add_symlink i386-linux-gnu /usr/lib32/libxcb-xfixes.so.0.0.0 libxcb-xfixes.so.0
add_symlink i386-linux-gnu /usr/lib32/libXdmcp.so.6.0.0 libXdmcp.so.6
add_symlink i386-linux-gnu /usr/lib32/libXext.so.6.4.0 libXext.so.6
add_symlink i386-linux-gnu /usr/lib32/libXfixes.so.3.1.0 libXfixes.so.3
add_symlink i386-linux-gnu /usr/lib32/libxkbcommon.so.0.10.0 libxkbcommon.so.0
add_symlink i386-linux-gnu /usr/lib32/libxml2.so.16.0.5 libxml2.so.16
add_symlink i386-linux-gnu /usr/lib32/libxshmfence.so.1.0.0 libxshmfence.so.1
add_symlink i386-linux-gnu /usr/lib32/libXxf86vm.so.1.0.0 libXxf86vm.so.1
add_symlink i386-linux-gnu /usr/lib32/libz.so.1.3.1 libz.so.1
add_symlink i386-linux-gnu /usr/lib32/libzstd.so.1.5.7 libzstd.so.1

passwd=$(cat <<EOF
${USER}:x:$(id -u):$(id -g)::/home/${USER}:/bin/bash
nobody:x:65534:65534:Nobody:/:/usr/bin/nologin
EOF
)

group=$(cat <<EOF
${USER}:x:$(id -g):
nobody:x:65534:
EOF
)

# Split arguments for bwrap and for exec
# Call with e.g. `minipv --ro-bind thing /thing -- /thing/run.sh --verbose`
bwrap_args=()
exec_cmd=()

while [ "$#" -gt 0 ]; do
  case "$1" in
    --)
      shift
      exec_cmd=("$@")
      break
      ;;
    *)
      bwrap_args+=("$1")
      shift
      ;;
  esac
done

if [ ${#exec_cmd[@]} -eq 0 ]; then
  exec_cmd=("bash")
fi

exec bwrap "${args[@]}" "${bwrap_args[@]}" -- sh -c 'ldconfig && exec "$@"' 'minipv' "${exec_cmd[@]}" \
  11<<< "$passwd" \
  12<<< "$group" \
  13<<< "ffffffffffffffffffffffffffffffff"
